nginx:
    image: nginx
    volumes:
        - ./site.template:/etc/nginx/conf.d/site.template
        - ./data:/data/www
    ports:
        - "8080:8080"
	- "8081:8081"
	- "8082:8082"
    environment:
        - NGINX_HOST=docker.adp.test
        - NGINX_PORT=8080
	- NGINX_PORT=8081
	- NGINX_PORT=8082
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always

